<?php /** @var $block Perspective\CrudM\Block\CrudBlock */ ?>

<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Content</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th colspan="3">Action</th>
    </tr>
    <?php
    $collection = $block->getResult();
    foreach ($collection as $item) {
        ?>
        <tr>
            <td><?php echo $item->getData('post_id'); ?></td>
            <td><?php echo $item->getData('name'); ?></td>
            <td><?php echo $item->getData('post_content'); ?></td>
            <td><?php echo $item->getData('created_at'); ?></td>
            <td><?php echo $item->getData('updated_at'); ?></td>
            <td><a href="<?php echo $block->getUrl('crudm/index/edit') . 'id/' . $item->getData('post_id'); ?>" class="action primary">Edit</a></td>
            <td><a href="<?php echo $block->getUrl('crudm/index/delid') . '?id=' . $item->getData('post_id'); ?>" class="action primary">Delete</a></td>
            <td><a href="<?php echo $block->getUrl('crudm/index/updateid') . '?id=' . $item->getData('post_id'); ?>" class="action primary">Update</a></td>
        </tr>
    <?php } ?>
</table>
<a class="action primary" href="<?php echo $block->getUrl('crudm/index/add'); ?>">Add Record</a>
<a class="action primary" href="<?php echo $block->getUrl('crudm/index/delete'); ?>">Delete All Record</a>